# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  release:
    types: [ created ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: install qt static
        uses: orestonce/install-qt-static@v0.4.3
        with:
          version: Qt6.5.3-Windows-x86_64-MinGW13.2.0-ucrt-staticFull-20240527
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.20.11 # optional
      - name: build  
        run: |
          go mod tidy
          go run export/main.go
          cd image2pdf-qt && qmake && mingw32-make release && cd ..
          dir image2pdf-qt\release\image2pdf-qt.exe
      - name: upload release
        uses: Guerra24/upload-to-release@v1
        with:
          name: image2pdf_qt_windows_x64-${{ github.ref_name }}.exe
          path: image2pdf-qt/release/image2pdf-qt.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}